# Generated by Django 4.1.5 on 2023-09-26 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reg_no',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator(regex='^[A-Z0-9]{2}-[A-Z0-9]{3}-[A-Z0-9]{2}$')]),
        ),
    ]
