# Generated by Django 2.1 on 2023-09-18 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='joinreq',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='mods',
            field=models.ManyToManyField(related_name='mod_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forum',
            name='users',
            field=models.ManyToManyField(related_name='forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='forum',
            field=models.ManyToManyField(blank=True, related_name='events', to='forums.Forum'),
        ),
        migrations.AddField(
            model_name='events',
            name='users_added',
            field=models.ManyToManyField(blank=True, related_name='events_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
