# Generated by Django 4.1.7 on 2023-09-23 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_alter_events_id_alter_forum_id_alter_forum_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='pic',
            field=models.ImageField(default='/forums/Dragonfruit2.jpg', upload_to='forums'),
        ),
    ]
