# Generated by Django 4.1.7 on 2023-09-25 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0004_alter_forum_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinreq',
            name='from_forum',
            field=models.BooleanField(default=False),
        ),
    ]
